version: '2.1'

services:
  grafana:
     extra_hosts:
        - "dockerhost:$DOCKERHOST"
     image: grafana/grafana

     ports:
         - 3000:3000
     environment:
        - "GF_SECURITY_ADMIN_PASSWORD=secret"
        - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
